services:
  - type: web
    name: atma-api
    env: docker
    dockerfilePath: ./Dockerfile
    dockerCommand: ./scripts/start-api.sh
    healthCheckPath: /health
    autoDeploy: false

  - type: worker
    name: atma-worker
    env: docker
    dockerfilePath: ./Dockerfile
    dockerCommand: ./scripts/start-worker.sh
    autoDeploy: false
